name: Build and Test Pipeline
on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: 'gcloud info'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: asia.gcr.io/fabled-citadel-342513/learn-go-echo:latest
      - name: Terraform Init
        run: 'terraform init'
      - name: Terraform Plan
        run: 'terraform plan'
      - name: Terraform Apply
        run: 'terraform apply -auto-approve'
