name: Build and Test Pipeline
on: [push]
jobs:
  Main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure Docker
        run: 'gcloud auth configure-docker asia.gcr.io -q'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asia.gcr.io/scheduled-chat-bot/learn-go-echo:latest
      - name: Initialize Terraform
        run: 'terraform init'
      - name: Apply Terraform
        run: 'terraform apply -auto-approve -replace=google_cloud_run_service.my_web_app'
